version: '3.8'

services:
  app:
    build: .
    container_name: sistema_Mototech
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/jboss/wildfly/standalone/log
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: Mototech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
