version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: mototech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - appnet

  wildfly-app:
    build: .
    container_name: wildfly-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - wildfly-logs:/opt/jboss/wildfly/standalone/log
    networks:
      - appnet

volumes:
  pgdata:
  wildfly-logs:

networks:
  appnet:
